name: data_layer
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  http: ^1.2.0
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
