name: lab2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/icons/
    # - resources/icons/avatar.svg
    # - resources/icons/doctor_avatar.svg
    - resources/images/
    # - resources/icons/eye.svg
    # - resources/icons/heart.svg
    # - resources/icons/tooth.svg
    # - resources/icons/lungs.svg
    # - resources/icons/stethoscope.svg
    # - resources/images/booking.png
    # - resources/images/consult.png
