name: lab2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.5
  json_dynamic_widget: ^10.0.0
  data_layer: 
    path: ./data_layer
  domain:
    path: ./domain
  presentation:
    path: ./presentation


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/icons/
    - resources/images/
    - resources/json/
