name: presentation
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.5
  json_dynamic_widget: ^10.0.0
  data_layer: 
    path: ../data_layer
  domain:
    path: ../domain
  


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
